version: '3'

services:
  apache:
    build: ./build
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - '8888:80'
    networks:
      - phpsite
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - phpsite  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8889:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - phpsite
networks:
  phpsite:
volumes:
  db_data: